name: CRYPTO TRADING AGENT

on:
  schedule:
    # Trading hours NYC: 7am, 9:30am, 11am, 3pm, 5pm, 7pm (UTC+4/5)
    - cron: "0 11 * * 1-5"   # 7:00 AM EST/EDT
    - cron: "30 13 * * 1-5"  # 9:30 AM EST/EDT  
    - cron: "0 15 * * 1-5"   # 11:00 AM EST/EDT
    - cron: "0 19 * * 1-5"   # 3:00 PM EST/EDT
    - cron: "0 21 * * 1-5"   # 5:00 PM EST/EDT
    - cron: "0 23 * * 1-5"   # 7:00 PM EST/EDT
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-trading-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run trading agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_WHATSAPP_NUMBER: ${{ secrets.TWILIO_WHATSAPP_NUMBER }}
          TWILIO_CONTENT_SID: ${{ secrets.TWILIO_CONTENT_SID }}
          WHATSAPP_RECIPIENT_NUMBER: ${{ secrets.WHATSAPP_RECIPIENT_NUMBER }}
          IACOB_MARKET_TYPE: CRYPTO
        run: npm start

      - name: Commit portfolio changes
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add portfolio_crypto.json README.md resource/output/
          git diff --staged --quiet || git commit -m ":loud_sound: Update portfolio crypto after trading session [skip ci]"
          git push
